"""empty message

Revision ID: 097d6eedce34
Revises: 
Create Date: 2021-09-18 07:55:41.307362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097d6eedce34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(length=64), nullable=False),
    sa.Column('studentNumber', sa.Integer(), nullable=False),
    sa.Column('unitCode', sa.String(length=8), nullable=False),
    sa.Column('enquiry', sa.Enum('Essay', 'Grammer', 'Lab Report', 'Assignment', 'Literature Research', 'Resaerch Proposal', 'Thesis/Paper', 'IELTS', 'Oral Presentation', 'Referencing', 'Finding Sources', 'Endnote', 'Other', name='enquiryType'), nullable=False),
    sa.Column('queue', sa.Enum('STUDYSmarter', 'Librarian', name='queueType'), nullable=False),
    sa.Column('status', sa.Enum('Ended', 'In Queue', 'In Session', 'Completed', name='statusEnum'), nullable=False),
    sa.Column('enterQueueTime', sa.DateTime(), nullable=False),
    sa.Column('changeSessionTime', sa.DateTime(), nullable=True),
    sa.Column('exitSessionTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Student Helper', name='roleEnum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('queue')
    # ### end Alembic commands ###
