"""empty message

Revision ID: 7afadc1c12f9
Revises: da2aa5fdc28a
Create Date: 2021-09-09 04:56:34.149164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7afadc1c12f9'
down_revision = 'da2aa5fdc28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enquiries')
    op.add_column('queue', sa.Column('enterQueueTime', sa.DateTime(), nullable=False))
    op.add_column('queue', sa.Column('changeSessionTime', sa.DateTime(), nullable=True))
    op.add_column('queue', sa.Column('exitSessionTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'exitSessionTime')
    op.drop_column('queue', 'changeSessionTime')
    op.drop_column('queue', 'enterQueueTime')
    op.create_table('enquiries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unitCode', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('enquiry', postgresql.ENUM('Essay', 'Grammer', 'Lab Report', 'Assignment', 'Literature Research', 'Resaerch Proposal', 'Thesis/Paper', 'IELTS', 'Oral Presentation', 'Referencing', 'Finding Sources', 'Endnote', 'Other', name='enquiryType'), autoincrement=False, nullable=False),
    sa.Column('queue', postgresql.ENUM('STUDYSmarter', 'Librarians', 'In Session', name='queueType'), autoincrement=False, nullable=False),
    sa.Column('enterQueueTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('changeSessionTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exitSessionTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='enquiries_pkey')
    )
    # ### end Alembic commands ###
