"""empty message

Revision ID: 882a5de2349a
Revises: 1bb20865694b
Create Date: 2021-09-18 07:45:44.317454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882a5de2349a'
down_revision = '1bb20865694b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(length=64), nullable=False),
    sa.Column('studentNumber', sa.Integer(), nullable=False),
    sa.Column('unitCode', sa.String(length=8), nullable=False),
    sa.Column('enquiry', sa.Enum('Essay', 'Grammer', 'Lab Report', 'Assignment', 'Literature Research', 'Resaerch Proposal', 'Thesis/Paper', 'IELTS', 'Oral Presentation', 'Referencing', 'Finding Sources', 'Endnote', 'Other', name='enquiryType'), nullable=False),
    sa.Column('queue', sa.Enum('STUDYSmarter', 'Librarian', name='queueType'), nullable=False),
    sa.Column('status', sa.Enum('Ended', 'In Queue', 'In Session', 'Completed', name='statusEnum'), nullable=False),
    sa.Column('enterQueueTime', sa.DateTime(), nullable=False),
    sa.Column('changeSessionTime', sa.DateTime(), nullable=True),
    sa.Column('exitSessionTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    # ### end Alembic commands ###
