"""empty message

Revision ID: da2aa5fdc28a
Revises: 17c916eaf732
Create Date: 2021-09-09 04:43:02.578999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2aa5fdc28a'
down_revision = '17c916eaf732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unitCode', sa.String(length=8), nullable=False),
    sa.Column('enquiry', sa.Enum('Essay', 'Grammer', 'Lab Report', 'Assignment', 'Literature Research', 'Resaerch Proposal', 'Thesis/Paper', 'IELTS', 'Oral Presentation', 'Referencing', 'Finding Sources', 'Endnote', 'Other', name='enquiryType'), nullable=False),
    sa.Column('queue', sa.Enum('STUDYSmarter', 'Librarians', 'In Session', name='queueType'), nullable=False),
    sa.Column('enterQueueTime', sa.DateTime(), nullable=False),
    sa.Column('changeSessionTime', sa.DateTime(), nullable=False),
    sa.Column('exitSessionTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(length=64), nullable=False),
    sa.Column('studentNumber', sa.Integer(), nullable=False),
    sa.Column('unitCode', sa.String(length=8), nullable=False),
    sa.Column('enquiry', sa.Enum('Essay', 'Grammer', 'Lab Report', 'Assignment', 'Literature Research', 'Resaerch Proposal', 'Thesis/Paper', 'IELTS', 'Oral Presentation', 'Referencing', 'Finding Sources', 'Endnote', 'Other', name='enquiryType'), nullable=False),
    sa.Column('queue', sa.Enum('STUDYSmarter', 'Librarians', 'In Session', name='queueType'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
