"""empty message

Revision ID: f316dd81d513
Revises: 8408aefd8f90
Create Date: 2021-09-30 12:53:58.766032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f316dd81d513'
down_revision = '8408aefd8f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_event_log',
    sa.Column('studentName', sa.String(length=64), nullable=False),
    sa.Column('studentNumber', sa.Integer(), nullable=False),
    sa.Column('unitCode', sa.String(length=8), nullable=False),
    sa.Column('enquiry', sa.Text(), nullable=False),
    sa.Column('queue', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('enterQueueTime', sa.DateTime(), nullable=False),
    sa.Column('changeSessionTime', sa.DateTime(), nullable=True),
    sa.Column('exitSessionTime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_session_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_event_log')
    # ### end Alembic commands ###
