# This configuration can be changed from this https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
# I will be putting comments on certain places where necessary

site_name: CITS3200 Project Team 18
copyright: Copyright Alex Mai, Jordan Hartley, Frinze Lapuz, Jake Yendell, Alex Hoffman, Liam Hovell
repo_url: https://github.com/UWA-CITS3200-18-2021/cits3200-project

# This uri refers to the github path to edit, change this if you branch is different in name
edit_uri: edit/main/mkdocs/docs/
theme:
  name: material
  custom_dir: overrides # remove this if you removed the override/partial
  palette:
  - media: "(prefers-color-scheme: light)" # below here is a palette for light mode
    primary: indigo
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"  # below here is a palette for dark mode
    primary: indigo
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

  logo: images/uwa.png
  favicon: images/uwa.png
  features: # Refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
      - navigation.instant
      - navigation.tabs
plugins:
  - search
  - mermaid2:
      version: 8.8.2
      arguments:
        theme: white # change this as you see fit - ["white", "dark"]
      
  # This is the PDF Generator of the documentation
  # More information here  https://github.com/orzih/mkdocs-with-pdf
  # note at this current moment, to use this feature, the following must be met
  # - Relative Path only with images
  # - Mermaid Markdown doesn't render at the moment in PDF
  - with-pdf:
      author: Alex Mai, Jordan Hartley, Frinze Lapuz, Jake Yendell, Alex Hoffman, Liam Hovell
      cover_title: CITS3200 Project Team 18
      cover_subtitle: UWA Academic Skills Drop-in - Client queue flow and usage reporting software
      cover_logo: ./docs/images/uwa_labelled.png
      enabled_if_env: ENABLE_PDF_EXPORT # This prevents generation of pdf when using `mkdocs serve` because it takes a long time. This will however generate the PDF when the environment variable is setup OR in the github action

# These are markdown extensions I have included that makes the documentation look nicer
# These extensions are from here https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tabbed
  - footnotes
  - pymdownx.critic
  - attr_list
  - def_list
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 4
  - codehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UWA-CITS3200-18-2021


# Add google Analytics when you need it
# Remove this if you dont need it
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
# google_analytics:
#   - UA-162451015-2 
#   - auto

# This is the extra javascript included in the documentation
extra_javascript:
  - https://unpkg.com/mermaid@8.8.2/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# If you want to put extra CSS
# extra_css:
#   - 

# This is where you adjust the hierarchy if the documentation
# You can erase this if you want. If you erase this, Mkdocs will alphabetically sort your documentation
nav:
- Overview: index.md
- User:
  - Overview: user/index.md
  - Functionality: user/functionality.md
  - Common Errors: user/common_errors.md
- Administrator:
  - Oveview: administrator/index.md
- Developer:
  - Overview: developer/index.md
  - Requirements: developer/requirements.md
  - Coding Patterns: developer/coding_patterns.md
  - Frontend/Client-Side App:
    - Overview: developer/frontend/index.md
  - Backend/Server-side App:
    - Overview: developer/backend/index.md
  - CI Pipeline: developer/ci_pipeline.md
  - Deployment: developer/deployment.md
# You can also create folder/file structure by following this syntax
# - Folder:
#   - Files : <Insert File here>